/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddPhotoToVehicleRequest model module.
 * @module model/AddPhotoToVehicleRequest
 * @version v0
 */
class AddPhotoToVehicleRequest {
    /**
     * Constructs a new <code>AddPhotoToVehicleRequest</code>.
     * @alias module:model/AddPhotoToVehicleRequest
     * @param photo {File} 
     */
    constructor(photo) { 
        
        AddPhotoToVehicleRequest.initialize(this, photo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, photo) { 
        obj['photo'] = photo;
    }

    /**
     * Constructs a <code>AddPhotoToVehicleRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddPhotoToVehicleRequest} obj Optional instance to populate.
     * @return {module:model/AddPhotoToVehicleRequest} The populated <code>AddPhotoToVehicleRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddPhotoToVehicleRequest();

            if (data.hasOwnProperty('photo')) {
                obj['photo'] = ApiClient.convertToType(data['photo'], File);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddPhotoToVehicleRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddPhotoToVehicleRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddPhotoToVehicleRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AddPhotoToVehicleRequest.RequiredProperties = ["photo"];

/**
 * @member {File} photo
 */
AddPhotoToVehicleRequest.prototype['photo'] = undefined;






export default AddPhotoToVehicleRequest;

