/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AdminPageDto model module.
 * @module model/AdminPageDto
 * @version v0
 */
class AdminPageDto {
    /**
     * Constructs a new <code>AdminPageDto</code>.
     * @alias module:model/AdminPageDto
     */
    constructor() { 
        
        AdminPageDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdminPageDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdminPageDto} obj Optional instance to populate.
     * @return {module:model/AdminPageDto} The populated <code>AdminPageDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdminPageDto();

            if (data.hasOwnProperty('homepageVisits')) {
                obj['homepageVisits'] = ApiClient.convertToType(data['homepageVisits'], 'Number');
            }
            if (data.hasOwnProperty('searchPageVisits')) {
                obj['searchPageVisits'] = ApiClient.convertToType(data['searchPageVisits'], 'Number');
            }
            if (data.hasOwnProperty('advertisementPageVisits')) {
                obj['advertisementPageVisits'] = ApiClient.convertToType(data['advertisementPageVisits'], 'Number');
            }
            if (data.hasOwnProperty('callButtonClicks')) {
                obj['callButtonClicks'] = ApiClient.convertToType(data['callButtonClicks'], 'Number');
            }
            if (data.hasOwnProperty('messageButtonClicks')) {
                obj['messageButtonClicks'] = ApiClient.convertToType(data['messageButtonClicks'], 'Number');
            }
            if (data.hasOwnProperty('dailyLogins')) {
                obj['dailyLogins'] = ApiClient.convertToType(data['dailyLogins'], 'Number');
            }
            if (data.hasOwnProperty('dailyRegistrations')) {
                obj['dailyRegistrations'] = ApiClient.convertToType(data['dailyRegistrations'], 'Number');
            }
            if (data.hasOwnProperty('avgTimeSpentOnSite')) {
                obj['avgTimeSpentOnSite'] = ApiClient.convertToType(data['avgTimeSpentOnSite'], 'Number');
            }
            if (data.hasOwnProperty('activeUsers')) {
                obj['activeUsers'] = ApiClient.convertToType(data['activeUsers'], 'Number');
            }
            if (data.hasOwnProperty('advertisementsAddedPerUser')) {
                obj['advertisementsAddedPerUser'] = ApiClient.convertToType(data['advertisementsAddedPerUser'], 'Number');
            }
            if (data.hasOwnProperty('advertisementEditsOrDeletions')) {
                obj['advertisementEditsOrDeletions'] = ApiClient.convertToType(data['advertisementEditsOrDeletions'], 'Number');
            }
            if (data.hasOwnProperty('mostViewedAdvertisements')) {
                obj['mostViewedAdvertisements'] = ApiClient.convertToType(data['mostViewedAdvertisements'], 'Number');
            }
            if (data.hasOwnProperty('totalUsers')) {
                obj['totalUsers'] = ApiClient.convertToType(data['totalUsers'], 'Number');
            }
            if (data.hasOwnProperty('activeUsersCount')) {
                obj['activeUsersCount'] = ApiClient.convertToType(data['activeUsersCount'], 'Number');
            }
            if (data.hasOwnProperty('totalAdvertisements')) {
                obj['totalAdvertisements'] = ApiClient.convertToType(data['totalAdvertisements'], 'Number');
            }
            if (data.hasOwnProperty('totalVehicles')) {
                obj['totalVehicles'] = ApiClient.convertToType(data['totalVehicles'], 'Number');
            }
            if (data.hasOwnProperty('usersWithRoleAdmin')) {
                obj['usersWithRoleAdmin'] = ApiClient.convertToType(data['usersWithRoleAdmin'], 'Number');
            }
            if (data.hasOwnProperty('usersWithRoleUser')) {
                obj['usersWithRoleUser'] = ApiClient.convertToType(data['usersWithRoleUser'], 'Number');
            }
            if (data.hasOwnProperty('inactiveUsers')) {
                obj['inactiveUsers'] = ApiClient.convertToType(data['inactiveUsers'], 'Number');
            }
            if (data.hasOwnProperty('usersWithMostAdvertisements')) {
                obj['usersWithMostAdvertisements'] = ApiClient.convertToType(data['usersWithMostAdvertisements'], ['String']);
            }
            if (data.hasOwnProperty('avgAdvertisementsPerUser')) {
                obj['avgAdvertisementsPerUser'] = ApiClient.convertToType(data['avgAdvertisementsPerUser'], 'Number');
            }
            if (data.hasOwnProperty('top5Brands')) {
                obj['top5Brands'] = ApiClient.convertToType(data['top5Brands'], ['String']);
            }
            if (data.hasOwnProperty('top5Models')) {
                obj['top5Models'] = ApiClient.convertToType(data['top5Models'], ['String']);
            }
            if (data.hasOwnProperty('fuelTypeDistribution')) {
                obj['fuelTypeDistribution'] = ApiClient.convertToType(data['fuelTypeDistribution'], ['String']);
            }
            if (data.hasOwnProperty('transmissionTypeDistribution')) {
                obj['transmissionTypeDistribution'] = ApiClient.convertToType(data['transmissionTypeDistribution'], ['String']);
            }
            if (data.hasOwnProperty('avgVehiclePrice')) {
                obj['avgVehiclePrice'] = ApiClient.convertToType(data['avgVehiclePrice'], 'Number');
            }
            if (data.hasOwnProperty('minVehiclePrice')) {
                obj['minVehiclePrice'] = ApiClient.convertToType(data['minVehiclePrice'], 'Number');
            }
            if (data.hasOwnProperty('maxVehiclePrice')) {
                obj['maxVehiclePrice'] = ApiClient.convertToType(data['maxVehiclePrice'], 'Number');
            }
            if (data.hasOwnProperty('medianVehiclePrice')) {
                obj['medianVehiclePrice'] = ApiClient.convertToType(data['medianVehiclePrice'], 'Number');
            }
            if (data.hasOwnProperty('minVehicleMileage')) {
                obj['minVehicleMileage'] = ApiClient.convertToType(data['minVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('maxVehicleMileage')) {
                obj['maxVehicleMileage'] = ApiClient.convertToType(data['maxVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('avgVehicleMileage')) {
                obj['avgVehicleMileage'] = ApiClient.convertToType(data['avgVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('vehiclesWithWarranty')) {
                obj['vehiclesWithWarranty'] = ApiClient.convertToType(data['vehiclesWithWarranty'], 'Number');
            }
            if (data.hasOwnProperty('newVehicles')) {
                obj['newVehicles'] = ApiClient.convertToType(data['newVehicles'], 'Number');
            }
            if (data.hasOwnProperty('usedVehicles')) {
                obj['usedVehicles'] = ApiClient.convertToType(data['usedVehicles'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdminPageDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdminPageDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['usersWithMostAdvertisements'])) {
            throw new Error("Expected the field `usersWithMostAdvertisements` to be an array in the JSON data but got " + data['usersWithMostAdvertisements']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['top5Brands'])) {
            throw new Error("Expected the field `top5Brands` to be an array in the JSON data but got " + data['top5Brands']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['top5Models'])) {
            throw new Error("Expected the field `top5Models` to be an array in the JSON data but got " + data['top5Models']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['fuelTypeDistribution'])) {
            throw new Error("Expected the field `fuelTypeDistribution` to be an array in the JSON data but got " + data['fuelTypeDistribution']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['transmissionTypeDistribution'])) {
            throw new Error("Expected the field `transmissionTypeDistribution` to be an array in the JSON data but got " + data['transmissionTypeDistribution']);
        }

        return true;
    }


}



/**
 * @member {Number} homepageVisits
 */
AdminPageDto.prototype['homepageVisits'] = undefined;

/**
 * @member {Number} searchPageVisits
 */
AdminPageDto.prototype['searchPageVisits'] = undefined;

/**
 * @member {Number} advertisementPageVisits
 */
AdminPageDto.prototype['advertisementPageVisits'] = undefined;

/**
 * @member {Number} callButtonClicks
 */
AdminPageDto.prototype['callButtonClicks'] = undefined;

/**
 * @member {Number} messageButtonClicks
 */
AdminPageDto.prototype['messageButtonClicks'] = undefined;

/**
 * @member {Number} dailyLogins
 */
AdminPageDto.prototype['dailyLogins'] = undefined;

/**
 * @member {Number} dailyRegistrations
 */
AdminPageDto.prototype['dailyRegistrations'] = undefined;

/**
 * @member {Number} avgTimeSpentOnSite
 */
AdminPageDto.prototype['avgTimeSpentOnSite'] = undefined;

/**
 * @member {Number} activeUsers
 */
AdminPageDto.prototype['activeUsers'] = undefined;

/**
 * @member {Number} advertisementsAddedPerUser
 */
AdminPageDto.prototype['advertisementsAddedPerUser'] = undefined;

/**
 * @member {Number} advertisementEditsOrDeletions
 */
AdminPageDto.prototype['advertisementEditsOrDeletions'] = undefined;

/**
 * @member {Number} mostViewedAdvertisements
 */
AdminPageDto.prototype['mostViewedAdvertisements'] = undefined;

/**
 * @member {Number} totalUsers
 */
AdminPageDto.prototype['totalUsers'] = undefined;

/**
 * @member {Number} activeUsersCount
 */
AdminPageDto.prototype['activeUsersCount'] = undefined;

/**
 * @member {Number} totalAdvertisements
 */
AdminPageDto.prototype['totalAdvertisements'] = undefined;

/**
 * @member {Number} totalVehicles
 */
AdminPageDto.prototype['totalVehicles'] = undefined;

/**
 * @member {Number} usersWithRoleAdmin
 */
AdminPageDto.prototype['usersWithRoleAdmin'] = undefined;

/**
 * @member {Number} usersWithRoleUser
 */
AdminPageDto.prototype['usersWithRoleUser'] = undefined;

/**
 * @member {Number} inactiveUsers
 */
AdminPageDto.prototype['inactiveUsers'] = undefined;

/**
 * @member {Array.<String>} usersWithMostAdvertisements
 */
AdminPageDto.prototype['usersWithMostAdvertisements'] = undefined;

/**
 * @member {Number} avgAdvertisementsPerUser
 */
AdminPageDto.prototype['avgAdvertisementsPerUser'] = undefined;

/**
 * @member {Array.<String>} top5Brands
 */
AdminPageDto.prototype['top5Brands'] = undefined;

/**
 * @member {Array.<String>} top5Models
 */
AdminPageDto.prototype['top5Models'] = undefined;

/**
 * @member {Array.<String>} fuelTypeDistribution
 */
AdminPageDto.prototype['fuelTypeDistribution'] = undefined;

/**
 * @member {Array.<String>} transmissionTypeDistribution
 */
AdminPageDto.prototype['transmissionTypeDistribution'] = undefined;

/**
 * @member {Number} avgVehiclePrice
 */
AdminPageDto.prototype['avgVehiclePrice'] = undefined;

/**
 * @member {Number} minVehiclePrice
 */
AdminPageDto.prototype['minVehiclePrice'] = undefined;

/**
 * @member {Number} maxVehiclePrice
 */
AdminPageDto.prototype['maxVehiclePrice'] = undefined;

/**
 * @member {Number} medianVehiclePrice
 */
AdminPageDto.prototype['medianVehiclePrice'] = undefined;

/**
 * @member {Number} minVehicleMileage
 */
AdminPageDto.prototype['minVehicleMileage'] = undefined;

/**
 * @member {Number} maxVehicleMileage
 */
AdminPageDto.prototype['maxVehicleMileage'] = undefined;

/**
 * @member {Number} avgVehicleMileage
 */
AdminPageDto.prototype['avgVehicleMileage'] = undefined;

/**
 * @member {Number} vehiclesWithWarranty
 */
AdminPageDto.prototype['vehiclesWithWarranty'] = undefined;

/**
 * @member {Number} newVehicles
 */
AdminPageDto.prototype['newVehicles'] = undefined;

/**
 * @member {Number} usedVehicles
 */
AdminPageDto.prototype['usedVehicles'] = undefined;






export default AdminPageDto;

