/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdvertisementDto from './AdvertisementDto';
import PageableObject from './PageableObject';
import SortObject from './SortObject';

/**
 * The PageAdvertisementDto model module.
 * @module model/PageAdvertisementDto
 * @version v0
 */
class PageAdvertisementDto {
    /**
     * Constructs a new <code>PageAdvertisementDto</code>.
     * @alias module:model/PageAdvertisementDto
     */
    constructor() { 
        
        PageAdvertisementDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageAdvertisementDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageAdvertisementDto} obj Optional instance to populate.
     * @return {module:model/PageAdvertisementDto} The populated <code>PageAdvertisementDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageAdvertisementDto();

            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [AdvertisementDto]);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('sort')) {
                obj['sort'] = ApiClient.convertToType(data['sort'], [SortObject]);
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
            if (data.hasOwnProperty('numberOfElements')) {
                obj['numberOfElements'] = ApiClient.convertToType(data['numberOfElements'], 'Number');
            }
            if (data.hasOwnProperty('pageable')) {
                obj['pageable'] = PageableObject.constructFromObject(data['pageable']);
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageAdvertisementDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageAdvertisementDto</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                AdvertisementDto.validateJSON(item);
            };
        }
        if (data['sort']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sort'])) {
                throw new Error("Expected the field `sort` to be an array in the JSON data but got " + data['sort']);
            }
            // validate the optional field `sort` (array)
            for (const item of data['sort']) {
                SortObject.validateJSON(item);
            };
        }
        // validate the optional field `pageable`
        if (data['pageable']) { // data not null
          PageableObject.validateJSON(data['pageable']);
        }

        return true;
    }


}



/**
 * @member {Number} totalPages
 */
PageAdvertisementDto.prototype['totalPages'] = undefined;

/**
 * @member {Number} totalElements
 */
PageAdvertisementDto.prototype['totalElements'] = undefined;

/**
 * @member {Number} size
 */
PageAdvertisementDto.prototype['size'] = undefined;

/**
 * @member {Array.<module:model/AdvertisementDto>} content
 */
PageAdvertisementDto.prototype['content'] = undefined;

/**
 * @member {Number} number
 */
PageAdvertisementDto.prototype['number'] = undefined;

/**
 * @member {Array.<module:model/SortObject>} sort
 */
PageAdvertisementDto.prototype['sort'] = undefined;

/**
 * @member {Boolean} first
 */
PageAdvertisementDto.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
PageAdvertisementDto.prototype['last'] = undefined;

/**
 * @member {Number} numberOfElements
 */
PageAdvertisementDto.prototype['numberOfElements'] = undefined;

/**
 * @member {module:model/PageableObject} pageable
 */
PageAdvertisementDto.prototype['pageable'] = undefined;

/**
 * @member {Boolean} empty
 */
PageAdvertisementDto.prototype['empty'] = undefined;






export default PageAdvertisementDto;

