/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserPageDto model module.
 * @module model/UserPageDto
 * @version v0
 */
class UserPageDto {
    /**
     * Constructs a new <code>UserPageDto</code>.
     * @alias module:model/UserPageDto
     */
    constructor() { 
        
        UserPageDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserPageDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserPageDto} obj Optional instance to populate.
     * @return {module:model/UserPageDto} The populated <code>UserPageDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserPageDto();

            if (data.hasOwnProperty('advertisementViews')) {
                obj['advertisementViews'] = ApiClient.convertToType(data['advertisementViews'], 'Number');
            }
            if (data.hasOwnProperty('callButtonClicks')) {
                obj['callButtonClicks'] = ApiClient.convertToType(data['callButtonClicks'], 'Number');
            }
            if (data.hasOwnProperty('messageButtonClicks')) {
                obj['messageButtonClicks'] = ApiClient.convertToType(data['messageButtonClicks'], 'Number');
            }
            if (data.hasOwnProperty('avgAdvertisementPrice')) {
                obj['avgAdvertisementPrice'] = ApiClient.convertToType(data['avgAdvertisementPrice'], 'Number');
            }
            if (data.hasOwnProperty('minAdvertisementPrice')) {
                obj['minAdvertisementPrice'] = ApiClient.convertToType(data['minAdvertisementPrice'], 'Number');
            }
            if (data.hasOwnProperty('maxAdvertisementPrice')) {
                obj['maxAdvertisementPrice'] = ApiClient.convertToType(data['maxAdvertisementPrice'], 'Number');
            }
            if (data.hasOwnProperty('medianAdvertisementPrice')) {
                obj['medianAdvertisementPrice'] = ApiClient.convertToType(data['medianAdvertisementPrice'], 'Number');
            }
            if (data.hasOwnProperty('avgVehicleMileage')) {
                obj['avgVehicleMileage'] = ApiClient.convertToType(data['avgVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('minVehicleMileage')) {
                obj['minVehicleMileage'] = ApiClient.convertToType(data['minVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('maxVehicleMileage')) {
                obj['maxVehicleMileage'] = ApiClient.convertToType(data['maxVehicleMileage'], 'Number');
            }
            if (data.hasOwnProperty('vehiclesWithWarranty')) {
                obj['vehiclesWithWarranty'] = ApiClient.convertToType(data['vehiclesWithWarranty'], 'Number');
            }
            if (data.hasOwnProperty('usedVsNewVehiclesPercentage')) {
                obj['usedVsNewVehiclesPercentage'] = ApiClient.convertToType(data['usedVsNewVehiclesPercentage'], 'Number');
            }
            if (data.hasOwnProperty('fuelTypeDistribution')) {
                obj['fuelTypeDistribution'] = ApiClient.convertToType(data['fuelTypeDistribution'], 'String');
            }
            if (data.hasOwnProperty('transmissionTypeDistribution')) {
                obj['transmissionTypeDistribution'] = ApiClient.convertToType(data['transmissionTypeDistribution'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserPageDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserPageDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fuelTypeDistribution'] && !(typeof data['fuelTypeDistribution'] === 'string' || data['fuelTypeDistribution'] instanceof String)) {
            throw new Error("Expected the field `fuelTypeDistribution` to be a primitive type in the JSON string but got " + data['fuelTypeDistribution']);
        }
        // ensure the json data is a string
        if (data['transmissionTypeDistribution'] && !(typeof data['transmissionTypeDistribution'] === 'string' || data['transmissionTypeDistribution'] instanceof String)) {
            throw new Error("Expected the field `transmissionTypeDistribution` to be a primitive type in the JSON string but got " + data['transmissionTypeDistribution']);
        }

        return true;
    }


}



/**
 * @member {Number} advertisementViews
 */
UserPageDto.prototype['advertisementViews'] = undefined;

/**
 * @member {Number} callButtonClicks
 */
UserPageDto.prototype['callButtonClicks'] = undefined;

/**
 * @member {Number} messageButtonClicks
 */
UserPageDto.prototype['messageButtonClicks'] = undefined;

/**
 * @member {Number} avgAdvertisementPrice
 */
UserPageDto.prototype['avgAdvertisementPrice'] = undefined;

/**
 * @member {Number} minAdvertisementPrice
 */
UserPageDto.prototype['minAdvertisementPrice'] = undefined;

/**
 * @member {Number} maxAdvertisementPrice
 */
UserPageDto.prototype['maxAdvertisementPrice'] = undefined;

/**
 * @member {Number} medianAdvertisementPrice
 */
UserPageDto.prototype['medianAdvertisementPrice'] = undefined;

/**
 * @member {Number} avgVehicleMileage
 */
UserPageDto.prototype['avgVehicleMileage'] = undefined;

/**
 * @member {Number} minVehicleMileage
 */
UserPageDto.prototype['minVehicleMileage'] = undefined;

/**
 * @member {Number} maxVehicleMileage
 */
UserPageDto.prototype['maxVehicleMileage'] = undefined;

/**
 * @member {Number} vehiclesWithWarranty
 */
UserPageDto.prototype['vehiclesWithWarranty'] = undefined;

/**
 * @member {Number} usedVsNewVehiclesPercentage
 */
UserPageDto.prototype['usedVsNewVehiclesPercentage'] = undefined;

/**
 * @member {String} fuelTypeDistribution
 */
UserPageDto.prototype['fuelTypeDistribution'] = undefined;

/**
 * @member {String} transmissionTypeDistribution
 */
UserPageDto.prototype['transmissionTypeDistribution'] = undefined;

/**
 * @member {Date} timestamp
 */
UserPageDto.prototype['timestamp'] = undefined;






export default UserPageDto;

