/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VehicleDto model module.
 * @module model/VehicleDto
 * @version v0
 */
class VehicleDto {
    /**
     * Constructs a new <code>VehicleDto</code>.
     * @alias module:model/VehicleDto
     * @param brand {String} 
     * @param model {String} 
     * @param year {Number} 
     * @param price {Number} 
     * @param fuelType {module:model/VehicleDto.FuelTypeEnum} 
     * @param transmission {module:model/VehicleDto.TransmissionEnum} 
     * @param color {String} 
     * @param vin {String} 
     * @param condition {module:model/VehicleDto.ConditionEnum} 
     * @param hasWarranty {Boolean} 
     * @param advertisementId {Number} 
     */
    constructor(brand, model, year, price, fuelType, transmission, color, vin, condition, hasWarranty, advertisementId) { 
        
        VehicleDto.initialize(this, brand, model, year, price, fuelType, transmission, color, vin, condition, hasWarranty, advertisementId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, brand, model, year, price, fuelType, transmission, color, vin, condition, hasWarranty, advertisementId) { 
        obj['brand'] = brand;
        obj['model'] = model;
        obj['year'] = year;
        obj['price'] = price;
        obj['fuelType'] = fuelType;
        obj['transmission'] = transmission;
        obj['color'] = color;
        obj['vin'] = vin;
        obj['condition'] = condition;
        obj['hasWarranty'] = hasWarranty;
        obj['advertisementId'] = advertisementId;
    }

    /**
     * Constructs a <code>VehicleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehicleDto} obj Optional instance to populate.
     * @return {module:model/VehicleDto} The populated <code>VehicleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehicleDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('brand')) {
                obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('fuelType')) {
                obj['fuelType'] = ApiClient.convertToType(data['fuelType'], 'String');
            }
            if (data.hasOwnProperty('transmission')) {
                obj['transmission'] = ApiClient.convertToType(data['transmission'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('mileage')) {
                obj['mileage'] = ApiClient.convertToType(data['mileage'], 'Number');
            }
            if (data.hasOwnProperty('power')) {
                obj['power'] = ApiClient.convertToType(data['power'], 'Number');
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
            }
            if (data.hasOwnProperty('hasWarranty')) {
                obj['hasWarranty'] = ApiClient.convertToType(data['hasWarranty'], 'Boolean');
            }
            if (data.hasOwnProperty('advertisementId')) {
                obj['advertisementId'] = ApiClient.convertToType(data['advertisementId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehicleDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehicleDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VehicleDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['brand'] && !(typeof data['brand'] === 'string' || data['brand'] instanceof String)) {
            throw new Error("Expected the field `brand` to be a primitive type in the JSON string but got " + data['brand']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['fuelType'] && !(typeof data['fuelType'] === 'string' || data['fuelType'] instanceof String)) {
            throw new Error("Expected the field `fuelType` to be a primitive type in the JSON string but got " + data['fuelType']);
        }
        // ensure the json data is a string
        if (data['transmission'] && !(typeof data['transmission'] === 'string' || data['transmission'] instanceof String)) {
            throw new Error("Expected the field `transmission` to be a primitive type in the JSON string but got " + data['transmission']);
        }
        // ensure the json data is a string
        if (data['color'] && !(typeof data['color'] === 'string' || data['color'] instanceof String)) {
            throw new Error("Expected the field `color` to be a primitive type in the JSON string but got " + data['color']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }
        // ensure the json data is a string
        if (data['condition'] && !(typeof data['condition'] === 'string' || data['condition'] instanceof String)) {
            throw new Error("Expected the field `condition` to be a primitive type in the JSON string but got " + data['condition']);
        }

        return true;
    }


}

VehicleDto.RequiredProperties = ["brand", "model", "year", "price", "fuelType", "transmission", "color", "vin", "condition", "hasWarranty", "advertisementId"];

/**
 * @member {Number} id
 */
VehicleDto.prototype['id'] = undefined;

/**
 * @member {String} brand
 */
VehicleDto.prototype['brand'] = undefined;

/**
 * @member {String} model
 */
VehicleDto.prototype['model'] = undefined;

/**
 * @member {Number} year
 */
VehicleDto.prototype['year'] = undefined;

/**
 * @member {Number} price
 */
VehicleDto.prototype['price'] = undefined;

/**
 * @member {module:model/VehicleDto.FuelTypeEnum} fuelType
 */
VehicleDto.prototype['fuelType'] = undefined;

/**
 * @member {module:model/VehicleDto.TransmissionEnum} transmission
 */
VehicleDto.prototype['transmission'] = undefined;

/**
 * @member {String} color
 */
VehicleDto.prototype['color'] = undefined;

/**
 * @member {Number} mileage
 */
VehicleDto.prototype['mileage'] = undefined;

/**
 * @member {Number} power
 */
VehicleDto.prototype['power'] = undefined;

/**
 * @member {Number} seats
 */
VehicleDto.prototype['seats'] = undefined;

/**
 * @member {String} description
 */
VehicleDto.prototype['description'] = undefined;

/**
 * @member {String} vin
 */
VehicleDto.prototype['vin'] = undefined;

/**
 * @member {module:model/VehicleDto.ConditionEnum} condition
 */
VehicleDto.prototype['condition'] = undefined;

/**
 * @member {Boolean} hasWarranty
 */
VehicleDto.prototype['hasWarranty'] = undefined;

/**
 * @member {Number} advertisementId
 */
VehicleDto.prototype['advertisementId'] = undefined;





/**
 * Allowed values for the <code>fuelType</code> property.
 * @enum {String}
 * @readonly
 */
VehicleDto['FuelTypeEnum'] = {

    /**
     * value: "PETROL"
     * @const
     */
    "PETROL": "PETROL",

    /**
     * value: "DIESEL"
     * @const
     */
    "DIESEL": "DIESEL",

    /**
     * value: "LPG"
     * @const
     */
    "LPG": "LPG",

    /**
     * value: "ELECTRIC"
     * @const
     */
    "ELECTRIC": "ELECTRIC",

    /**
     * value: "HYBRID"
     * @const
     */
    "HYBRID": "HYBRID"
};


/**
 * Allowed values for the <code>transmission</code> property.
 * @enum {String}
 * @readonly
 */
VehicleDto['TransmissionEnum'] = {

    /**
     * value: "MANUAL"
     * @const
     */
    "MANUAL": "MANUAL",

    /**
     * value: "AUTOMATIC"
     * @const
     */
    "AUTOMATIC": "AUTOMATIC"
};


/**
 * Allowed values for the <code>condition</code> property.
 * @enum {String}
 * @readonly
 */
VehicleDto['ConditionEnum'] = {

    /**
     * value: "NEW"
     * @const
     */
    "NEW": "NEW",

    /**
     * value: "USED"
     * @const
     */
    "USED": "USED",

    /**
     * value: "DAMAGED"
     * @const
     */
    "DAMAGED": "DAMAGED"
};



export default VehicleDto;

