/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Advertisement from './Advertisement';

/**
 * The Vehicle model module.
 * @module model/Vehicle
 * @version v0
 */
class Vehicle {
    /**
     * Constructs a new <code>Vehicle</code>.
     * @alias module:model/Vehicle
     */
    constructor() { 
        
        Vehicle.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Vehicle</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vehicle} obj Optional instance to populate.
     * @return {module:model/Vehicle} The populated <code>Vehicle</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vehicle();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('brand')) {
                obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('fuelType')) {
                obj['fuelType'] = ApiClient.convertToType(data['fuelType'], 'String');
            }
            if (data.hasOwnProperty('transmission')) {
                obj['transmission'] = ApiClient.convertToType(data['transmission'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('mileage')) {
                obj['mileage'] = ApiClient.convertToType(data['mileage'], 'Number');
            }
            if (data.hasOwnProperty('power')) {
                obj['power'] = ApiClient.convertToType(data['power'], 'Number');
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
            }
            if (data.hasOwnProperty('hasWarranty')) {
                obj['hasWarranty'] = ApiClient.convertToType(data['hasWarranty'], 'Boolean');
            }
            if (data.hasOwnProperty('advertisement')) {
                obj['advertisement'] = Advertisement.constructFromObject(data['advertisement']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Vehicle</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Vehicle</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['brand'] && !(typeof data['brand'] === 'string' || data['brand'] instanceof String)) {
            throw new Error("Expected the field `brand` to be a primitive type in the JSON string but got " + data['brand']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }
        // ensure the json data is a string
        if (data['fuelType'] && !(typeof data['fuelType'] === 'string' || data['fuelType'] instanceof String)) {
            throw new Error("Expected the field `fuelType` to be a primitive type in the JSON string but got " + data['fuelType']);
        }
        // ensure the json data is a string
        if (data['transmission'] && !(typeof data['transmission'] === 'string' || data['transmission'] instanceof String)) {
            throw new Error("Expected the field `transmission` to be a primitive type in the JSON string but got " + data['transmission']);
        }
        // ensure the json data is a string
        if (data['color'] && !(typeof data['color'] === 'string' || data['color'] instanceof String)) {
            throw new Error("Expected the field `color` to be a primitive type in the JSON string but got " + data['color']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['vin'] && !(typeof data['vin'] === 'string' || data['vin'] instanceof String)) {
            throw new Error("Expected the field `vin` to be a primitive type in the JSON string but got " + data['vin']);
        }
        // ensure the json data is a string
        if (data['condition'] && !(typeof data['condition'] === 'string' || data['condition'] instanceof String)) {
            throw new Error("Expected the field `condition` to be a primitive type in the JSON string but got " + data['condition']);
        }
        // validate the optional field `advertisement`
        if (data['advertisement']) { // data not null
          Advertisement.validateJSON(data['advertisement']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Vehicle.prototype['id'] = undefined;

/**
 * @member {String} brand
 */
Vehicle.prototype['brand'] = undefined;

/**
 * @member {String} model
 */
Vehicle.prototype['model'] = undefined;

/**
 * @member {Number} year
 */
Vehicle.prototype['year'] = undefined;

/**
 * @member {Number} price
 */
Vehicle.prototype['price'] = undefined;

/**
 * @member {module:model/Vehicle.FuelTypeEnum} fuelType
 */
Vehicle.prototype['fuelType'] = undefined;

/**
 * @member {module:model/Vehicle.TransmissionEnum} transmission
 */
Vehicle.prototype['transmission'] = undefined;

/**
 * @member {String} color
 */
Vehicle.prototype['color'] = undefined;

/**
 * @member {Number} mileage
 */
Vehicle.prototype['mileage'] = undefined;

/**
 * @member {Number} power
 */
Vehicle.prototype['power'] = undefined;

/**
 * @member {Number} seats
 */
Vehicle.prototype['seats'] = undefined;

/**
 * @member {String} description
 */
Vehicle.prototype['description'] = undefined;

/**
 * @member {String} vin
 */
Vehicle.prototype['vin'] = undefined;

/**
 * @member {module:model/Vehicle.ConditionEnum} condition
 */
Vehicle.prototype['condition'] = undefined;

/**
 * @member {Boolean} hasWarranty
 */
Vehicle.prototype['hasWarranty'] = undefined;

/**
 * @member {module:model/Advertisement} advertisement
 */
Vehicle.prototype['advertisement'] = undefined;





/**
 * Allowed values for the <code>fuelType</code> property.
 * @enum {String}
 * @readonly
 */
Vehicle['FuelTypeEnum'] = {

    /**
     * value: "PETROL"
     * @const
     */
    "PETROL": "PETROL",

    /**
     * value: "DIESEL"
     * @const
     */
    "DIESEL": "DIESEL",

    /**
     * value: "LPG"
     * @const
     */
    "LPG": "LPG",

    /**
     * value: "ELECTRIC"
     * @const
     */
    "ELECTRIC": "ELECTRIC",

    /**
     * value: "HYBRID"
     * @const
     */
    "HYBRID": "HYBRID"
};


/**
 * Allowed values for the <code>transmission</code> property.
 * @enum {String}
 * @readonly
 */
Vehicle['TransmissionEnum'] = {

    /**
     * value: "MANUAL"
     * @const
     */
    "MANUAL": "MANUAL",

    /**
     * value: "AUTOMATIC"
     * @const
     */
    "AUTOMATIC": "AUTOMATIC"
};


/**
 * Allowed values for the <code>condition</code> property.
 * @enum {String}
 * @readonly
 */
Vehicle['ConditionEnum'] = {

    /**
     * value: "NEW"
     * @const
     */
    "NEW": "NEW",

    /**
     * value: "USED"
     * @const
     */
    "USED": "USED",

    /**
     * value: "DAMAGED"
     * @const
     */
    "DAMAGED": "DAMAGED"
};



export default Vehicle;

