/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Vehicle from './Vehicle';

/**
 * The VehiclePhoto model module.
 * @module model/VehiclePhoto
 * @version v0
 */
class VehiclePhoto {
    /**
     * Constructs a new <code>VehiclePhoto</code>.
     * @alias module:model/VehiclePhoto
     */
    constructor() { 
        
        VehiclePhoto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VehiclePhoto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehiclePhoto} obj Optional instance to populate.
     * @return {module:model/VehiclePhoto} The populated <code>VehiclePhoto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehiclePhoto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('photoUrl')) {
                obj['photoUrl'] = ApiClient.convertToType(data['photoUrl'], 'String');
            }
            if (data.hasOwnProperty('isMain')) {
                obj['isMain'] = ApiClient.convertToType(data['isMain'], 'Boolean');
            }
            if (data.hasOwnProperty('vehicle')) {
                obj['vehicle'] = Vehicle.constructFromObject(data['vehicle']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehiclePhoto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehiclePhoto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['photoUrl'] && !(typeof data['photoUrl'] === 'string' || data['photoUrl'] instanceof String)) {
            throw new Error("Expected the field `photoUrl` to be a primitive type in the JSON string but got " + data['photoUrl']);
        }
        // validate the optional field `vehicle`
        if (data['vehicle']) { // data not null
          Vehicle.validateJSON(data['vehicle']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
VehiclePhoto.prototype['id'] = undefined;

/**
 * @member {String} photoUrl
 */
VehiclePhoto.prototype['photoUrl'] = undefined;

/**
 * @member {Boolean} isMain
 */
VehiclePhoto.prototype['isMain'] = undefined;

/**
 * @member {module:model/Vehicle} vehicle
 */
VehiclePhoto.prototype['vehicle'] = undefined;






export default VehiclePhoto;

