/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VehiclePhotoDto model module.
 * @module model/VehiclePhotoDto
 * @version v0
 */
class VehiclePhotoDto {
    /**
     * Constructs a new <code>VehiclePhotoDto</code>.
     * @alias module:model/VehiclePhotoDto
     */
    constructor() { 
        
        VehiclePhotoDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VehiclePhotoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VehiclePhotoDto} obj Optional instance to populate.
     * @return {module:model/VehiclePhotoDto} The populated <code>VehiclePhotoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VehiclePhotoDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('photoUrl')) {
                obj['photoUrl'] = ApiClient.convertToType(data['photoUrl'], 'String');
            }
            if (data.hasOwnProperty('vehicleId')) {
                obj['vehicleId'] = ApiClient.convertToType(data['vehicleId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VehiclePhotoDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VehiclePhotoDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['photoUrl'] && !(typeof data['photoUrl'] === 'string' || data['photoUrl'] instanceof String)) {
            throw new Error("Expected the field `photoUrl` to be a primitive type in the JSON string but got " + data['photoUrl']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
VehiclePhotoDto.prototype['id'] = undefined;

/**
 * @member {String} photoUrl
 */
VehiclePhotoDto.prototype['photoUrl'] = undefined;

/**
 * @member {Number} vehicleId
 */
VehiclePhotoDto.prototype['vehicleId'] = undefined;






export default VehiclePhotoDto;

