/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.AdminPageDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminPageDto', function() {
    it('should create an instance of AdminPageDto', function() {
      // uncomment below and update the code to test AdminPageDto
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be.a(OpenApiDefinition.AdminPageDto);
    });

    it('should have the property homepageVisits (base name: "homepageVisits")', function() {
      // uncomment below and update the code to test the property homepageVisits
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property searchPageVisits (base name: "searchPageVisits")', function() {
      // uncomment below and update the code to test the property searchPageVisits
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property advertisementPageVisits (base name: "advertisementPageVisits")', function() {
      // uncomment below and update the code to test the property advertisementPageVisits
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property callButtonClicks (base name: "callButtonClicks")', function() {
      // uncomment below and update the code to test the property callButtonClicks
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property messageButtonClicks (base name: "messageButtonClicks")', function() {
      // uncomment below and update the code to test the property messageButtonClicks
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property dailyLogins (base name: "dailyLogins")', function() {
      // uncomment below and update the code to test the property dailyLogins
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property dailyRegistrations (base name: "dailyRegistrations")', function() {
      // uncomment below and update the code to test the property dailyRegistrations
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgTimeSpentOnSite (base name: "avgTimeSpentOnSite")', function() {
      // uncomment below and update the code to test the property avgTimeSpentOnSite
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property activeUsers (base name: "activeUsers")', function() {
      // uncomment below and update the code to test the property activeUsers
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property advertisementsAddedPerUser (base name: "advertisementsAddedPerUser")', function() {
      // uncomment below and update the code to test the property advertisementsAddedPerUser
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property advertisementEditsOrDeletions (base name: "advertisementEditsOrDeletions")', function() {
      // uncomment below and update the code to test the property advertisementEditsOrDeletions
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property mostViewedAdvertisements (base name: "mostViewedAdvertisements")', function() {
      // uncomment below and update the code to test the property mostViewedAdvertisements
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property totalUsers (base name: "totalUsers")', function() {
      // uncomment below and update the code to test the property totalUsers
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property activeUsersCount (base name: "activeUsersCount")', function() {
      // uncomment below and update the code to test the property activeUsersCount
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property totalAdvertisements (base name: "totalAdvertisements")', function() {
      // uncomment below and update the code to test the property totalAdvertisements
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property totalVehicles (base name: "totalVehicles")', function() {
      // uncomment below and update the code to test the property totalVehicles
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property usersWithRoleAdmin (base name: "usersWithRoleAdmin")', function() {
      // uncomment below and update the code to test the property usersWithRoleAdmin
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property usersWithRoleUser (base name: "usersWithRoleUser")', function() {
      // uncomment below and update the code to test the property usersWithRoleUser
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property inactiveUsers (base name: "inactiveUsers")', function() {
      // uncomment below and update the code to test the property inactiveUsers
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property usersWithMostAdvertisements (base name: "usersWithMostAdvertisements")', function() {
      // uncomment below and update the code to test the property usersWithMostAdvertisements
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgAdvertisementsPerUser (base name: "avgAdvertisementsPerUser")', function() {
      // uncomment below and update the code to test the property avgAdvertisementsPerUser
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property top5Brands (base name: "top5Brands")', function() {
      // uncomment below and update the code to test the property top5Brands
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property top5Models (base name: "top5Models")', function() {
      // uncomment below and update the code to test the property top5Models
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property fuelTypeDistribution (base name: "fuelTypeDistribution")', function() {
      // uncomment below and update the code to test the property fuelTypeDistribution
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property transmissionTypeDistribution (base name: "transmissionTypeDistribution")', function() {
      // uncomment below and update the code to test the property transmissionTypeDistribution
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgVehiclePrice (base name: "avgVehiclePrice")', function() {
      // uncomment below and update the code to test the property avgVehiclePrice
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property minVehiclePrice (base name: "minVehiclePrice")', function() {
      // uncomment below and update the code to test the property minVehiclePrice
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property maxVehiclePrice (base name: "maxVehiclePrice")', function() {
      // uncomment below and update the code to test the property maxVehiclePrice
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property medianVehiclePrice (base name: "medianVehiclePrice")', function() {
      // uncomment below and update the code to test the property medianVehiclePrice
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property minVehicleMileage (base name: "minVehicleMileage")', function() {
      // uncomment below and update the code to test the property minVehicleMileage
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property maxVehicleMileage (base name: "maxVehicleMileage")', function() {
      // uncomment below and update the code to test the property maxVehicleMileage
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgVehicleMileage (base name: "avgVehicleMileage")', function() {
      // uncomment below and update the code to test the property avgVehicleMileage
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property vehiclesWithWarranty (base name: "vehiclesWithWarranty")', function() {
      // uncomment below and update the code to test the property vehiclesWithWarranty
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property newVehicles (base name: "newVehicles")', function() {
      // uncomment below and update the code to test the property newVehicles
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

    it('should have the property usedVehicles (base name: "usedVehicles")', function() {
      // uncomment below and update the code to test the property usedVehicles
      //var instance = new OpenApiDefinition.AdminPageDto();
      //expect(instance).to.be();
    });

  });

}));
