/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be.a(OpenApiDefinition.User);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property advertisements (base name: "advertisements")', function() {
      // uncomment below and update the code to test the property advertisements
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property favorites (base name: "favorites")', function() {
      // uncomment below and update the code to test the property favorites
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property authorities (base name: "authorities")', function() {
      // uncomment below and update the code to test the property authorities
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property accountNonExpired (base name: "accountNonExpired")', function() {
      // uncomment below and update the code to test the property accountNonExpired
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property accountNonLocked (base name: "accountNonLocked")', function() {
      // uncomment below and update the code to test the property accountNonLocked
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

    it('should have the property credentialsNonExpired (base name: "credentialsNonExpired")', function() {
      // uncomment below and update the code to test the property credentialsNonExpired
      //var instance = new OpenApiDefinition.User();
      //expect(instance).to.be();
    });

  });

}));
