/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.UserPageDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPageDto', function() {
    it('should create an instance of UserPageDto', function() {
      // uncomment below and update the code to test UserPageDto
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be.a(OpenApiDefinition.UserPageDto);
    });

    it('should have the property advertisementViews (base name: "advertisementViews")', function() {
      // uncomment below and update the code to test the property advertisementViews
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property callButtonClicks (base name: "callButtonClicks")', function() {
      // uncomment below and update the code to test the property callButtonClicks
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property messageButtonClicks (base name: "messageButtonClicks")', function() {
      // uncomment below and update the code to test the property messageButtonClicks
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgAdvertisementPrice (base name: "avgAdvertisementPrice")', function() {
      // uncomment below and update the code to test the property avgAdvertisementPrice
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property minAdvertisementPrice (base name: "minAdvertisementPrice")', function() {
      // uncomment below and update the code to test the property minAdvertisementPrice
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property maxAdvertisementPrice (base name: "maxAdvertisementPrice")', function() {
      // uncomment below and update the code to test the property maxAdvertisementPrice
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property medianAdvertisementPrice (base name: "medianAdvertisementPrice")', function() {
      // uncomment below and update the code to test the property medianAdvertisementPrice
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property avgVehicleMileage (base name: "avgVehicleMileage")', function() {
      // uncomment below and update the code to test the property avgVehicleMileage
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property minVehicleMileage (base name: "minVehicleMileage")', function() {
      // uncomment below and update the code to test the property minVehicleMileage
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property maxVehicleMileage (base name: "maxVehicleMileage")', function() {
      // uncomment below and update the code to test the property maxVehicleMileage
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property vehiclesWithWarranty (base name: "vehiclesWithWarranty")', function() {
      // uncomment below and update the code to test the property vehiclesWithWarranty
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property usedVsNewVehiclesPercentage (base name: "usedVsNewVehiclesPercentage")', function() {
      // uncomment below and update the code to test the property usedVsNewVehiclesPercentage
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property fuelTypeDistribution (base name: "fuelTypeDistribution")', function() {
      // uncomment below and update the code to test the property fuelTypeDistribution
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property transmissionTypeDistribution (base name: "transmissionTypeDistribution")', function() {
      // uncomment below and update the code to test the property transmissionTypeDistribution
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new OpenApiDefinition.UserPageDto();
      //expect(instance).to.be();
    });

  });

}));
