/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.VehicleDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleDto', function() {
    it('should create an instance of VehicleDto', function() {
      // uncomment below and update the code to test VehicleDto
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be.a(OpenApiDefinition.VehicleDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property brand (base name: "brand")', function() {
      // uncomment below and update the code to test the property brand
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property fuelType (base name: "fuelType")', function() {
      // uncomment below and update the code to test the property fuelType
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property transmission (base name: "transmission")', function() {
      // uncomment below and update the code to test the property transmission
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property mileage (base name: "mileage")', function() {
      // uncomment below and update the code to test the property mileage
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property power (base name: "power")', function() {
      // uncomment below and update the code to test the property power
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property seats (base name: "seats")', function() {
      // uncomment below and update the code to test the property seats
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property vin (base name: "vin")', function() {
      // uncomment below and update the code to test the property vin
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property condition (base name: "condition")', function() {
      // uncomment below and update the code to test the property condition
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property hasWarranty (base name: "hasWarranty")', function() {
      // uncomment below and update the code to test the property hasWarranty
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

    it('should have the property advertisementId (base name: "advertisementId")', function() {
      // uncomment below and update the code to test the property advertisementId
      //var instance = new OpenApiDefinition.VehicleDto();
      //expect(instance).to.be();
    });

  });

}));
