/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddPhotoToVehicleRequest from './model/AddPhotoToVehicleRequest';
import AdminPageDto from './model/AdminPageDto';
import Advertisement from './model/Advertisement';
import AdvertisementDto from './model/AdvertisementDto';
import EmailDto from './model/EmailDto';
import GrantedAuthority from './model/GrantedAuthority';
import PageAdvertisementDto from './model/PageAdvertisementDto';
import Pageable from './model/Pageable';
import PageableObject from './model/PageableObject';
import SortObject from './model/SortObject';
import User from './model/User';
import UserDto from './model/UserDto';
import UserPageDto from './model/UserPageDto';
import Vehicle from './model/Vehicle';
import VehicleDto from './model/VehicleDto';
import VehiclePhoto from './model/VehiclePhoto';
import VehiclePhotoDto from './model/VehiclePhotoDto';
import AdminPageControllerApi from './api/AdminPageControllerApi';
import AdvertisementControllerApi from './api/AdvertisementControllerApi';
import EmailControllerApi from './api/EmailControllerApi';
import UserControllerApi from './api/UserControllerApi';
import UserPageControllerApi from './api/UserPageControllerApi';
import VehicleControllerApi from './api/VehicleControllerApi';
import VehiclePhotoControllerApi from './api/VehiclePhotoControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddPhotoToVehicleRequest model constructor.
     * @property {module:model/AddPhotoToVehicleRequest}
     */
    AddPhotoToVehicleRequest,

    /**
     * The AdminPageDto model constructor.
     * @property {module:model/AdminPageDto}
     */
    AdminPageDto,

    /**
     * The Advertisement model constructor.
     * @property {module:model/Advertisement}
     */
    Advertisement,

    /**
     * The AdvertisementDto model constructor.
     * @property {module:model/AdvertisementDto}
     */
    AdvertisementDto,

    /**
     * The EmailDto model constructor.
     * @property {module:model/EmailDto}
     */
    EmailDto,

    /**
     * The GrantedAuthority model constructor.
     * @property {module:model/GrantedAuthority}
     */
    GrantedAuthority,

    /**
     * The PageAdvertisementDto model constructor.
     * @property {module:model/PageAdvertisementDto}
     */
    PageAdvertisementDto,

    /**
     * The Pageable model constructor.
     * @property {module:model/Pageable}
     */
    Pageable,

    /**
     * The PageableObject model constructor.
     * @property {module:model/PageableObject}
     */
    PageableObject,

    /**
     * The SortObject model constructor.
     * @property {module:model/SortObject}
     */
    SortObject,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserDto model constructor.
     * @property {module:model/UserDto}
     */
    UserDto,

    /**
     * The UserPageDto model constructor.
     * @property {module:model/UserPageDto}
     */
    UserPageDto,

    /**
     * The Vehicle model constructor.
     * @property {module:model/Vehicle}
     */
    Vehicle,

    /**
     * The VehicleDto model constructor.
     * @property {module:model/VehicleDto}
     */
    VehicleDto,

    /**
     * The VehiclePhoto model constructor.
     * @property {module:model/VehiclePhoto}
     */
    VehiclePhoto,

    /**
     * The VehiclePhotoDto model constructor.
     * @property {module:model/VehiclePhotoDto}
     */
    VehiclePhotoDto,

    /**
    * The AdminPageControllerApi service constructor.
    * @property {module:api/AdminPageControllerApi}
    */
    AdminPageControllerApi,

    /**
    * The AdvertisementControllerApi service constructor.
    * @property {module:api/AdvertisementControllerApi}
    */
    AdvertisementControllerApi,

    /**
    * The EmailControllerApi service constructor.
    * @property {module:api/EmailControllerApi}
    */
    EmailControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi,

    /**
    * The UserPageControllerApi service constructor.
    * @property {module:api/UserPageControllerApi}
    */
    UserPageControllerApi,

    /**
    * The VehicleControllerApi service constructor.
    * @property {module:api/VehicleControllerApi}
    */
    VehicleControllerApi,

    /**
    * The VehiclePhotoControllerApi service constructor.
    * @property {module:api/VehiclePhotoControllerApi}
    */
    VehiclePhotoControllerApi
};
