/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.AdminPageControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminPageControllerApi', function() {
    describe('addPhotoToVehicle1', function() {
      it('should call addPhotoToVehicle1 successfully', function(done) {
        //uncomment below and update the code to test addPhotoToVehicle1
        //instance.addPhotoToVehicle1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addToFavorites2', function() {
      it('should call addToFavorites2 successfully', function(done) {
        //uncomment below and update the code to test addToFavorites2
        //instance.addToFavorites2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAdvertisement1', function() {
      it('should call createAdvertisement1 successfully', function(done) {
        //uncomment below and update the code to test createAdvertisement1
        //instance.createAdvertisement1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUser1', function() {
      it('should call createUser1 successfully', function(done) {
        //uncomment below and update the code to test createUser1
        //instance.createUser1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createVehicle1', function() {
      it('should call createVehicle1 successfully', function(done) {
        //uncomment below and update the code to test createVehicle1
        //instance.createVehicle1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAdvertisement1', function() {
      it('should call deleteAdvertisement1 successfully', function(done) {
        //uncomment below and update the code to test deleteAdvertisement1
        //instance.deleteAdvertisement1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePhoto1', function() {
      it('should call deletePhoto1 successfully', function(done) {
        //uncomment below and update the code to test deletePhoto1
        //instance.deletePhoto1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUser1', function() {
      it('should call deleteUser1 successfully', function(done) {
        //uncomment below and update the code to test deleteUser1
        //instance.deleteUser1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVehicle1', function() {
      it('should call deleteVehicle1 successfully', function(done) {
        //uncomment below and update the code to test deleteVehicle1
        //instance.deleteVehicle1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAdvertisementById1', function() {
      it('should call getAdvertisementById1 successfully', function(done) {
        //uncomment below and update the code to test getAdvertisementById1
        //instance.getAdvertisementById1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAdvertisementsByUser', function() {
      it('should call getAdvertisementsByUser successfully', function(done) {
        //uncomment below and update the code to test getAdvertisementsByUser
        //instance.getAdvertisementsByUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllAdvertisements', function() {
      it('should call getAllAdvertisements successfully', function(done) {
        //uncomment below and update the code to test getAllAdvertisements
        //instance.getAllAdvertisements(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllPhotos1', function() {
      it('should call getAllPhotos1 successfully', function(done) {
        //uncomment below and update the code to test getAllPhotos1
        //instance.getAllPhotos1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsers1', function() {
      it('should call getAllUsers1 successfully', function(done) {
        //uncomment below and update the code to test getAllUsers1
        //instance.getAllUsers1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllVehicles', function() {
      it('should call getAllVehicles successfully', function(done) {
        //uncomment below and update the code to test getAllVehicles
        //instance.getAllVehicles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDashboard', function() {
      it('should call getDashboard successfully', function(done) {
        //uncomment below and update the code to test getDashboard
        //instance.getDashboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavorites2', function() {
      it('should call getFavorites2 successfully', function(done) {
        //uncomment below and update the code to test getFavorites2
        //instance.getFavorites2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFilteredVehicles1', function() {
      it('should call getFilteredVehicles1 successfully', function(done) {
        //uncomment below and update the code to test getFilteredVehicles1
        //instance.getFilteredVehicles1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPhotoById1', function() {
      it('should call getPhotoById1 successfully', function(done) {
        //uncomment below and update the code to test getPhotoById1
        //instance.getPhotoById1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSortedVehicles1', function() {
      it('should call getSortedVehicles1 successfully', function(done) {
        //uncomment below and update the code to test getSortedVehicles1
        //instance.getSortedVehicles1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserById1', function() {
      it('should call getUserById1 successfully', function(done) {
        //uncomment below and update the code to test getUserById1
        //instance.getUserById1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehicleById1', function() {
      it('should call getVehicleById1 successfully', function(done) {
        //uncomment below and update the code to test getVehicleById1
        //instance.getVehicleById1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehiclesByUser', function() {
      it('should call getVehiclesByUser successfully', function(done) {
        //uncomment below and update the code to test getVehiclesByUser
        //instance.getVehiclesByUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeFromFavorites2', function() {
      it('should call removeFromFavorites2 successfully', function(done) {
        //uncomment below and update the code to test removeFromFavorites2
        //instance.removeFromFavorites2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAdvertisement1', function() {
      it('should call updateAdvertisement1 successfully', function(done) {
        //uncomment below and update the code to test updateAdvertisement1
        //instance.updateAdvertisement1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUser1', function() {
      it('should call updateUser1 successfully', function(done) {
        //uncomment below and update the code to test updateUser1
        //instance.updateUser1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVehicle1', function() {
      it('should call updateVehicle1 successfully', function(done) {
        //uncomment below and update the code to test updateVehicle1
        //instance.updateVehicle1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
