/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.UserPageControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserPageControllerApi', function() {
    describe('addToFavorites1', function() {
      it('should call addToFavorites1 successfully', function(done) {
        //uncomment below and update the code to test addToFavorites1
        //instance.addToFavorites1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUserAdvertisement', function() {
      it('should call createUserAdvertisement successfully', function(done) {
        //uncomment below and update the code to test createUserAdvertisement
        //instance.createUserAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUserVehicle', function() {
      it('should call createUserVehicle successfully', function(done) {
        //uncomment below and update the code to test createUserVehicle
        //instance.createUserVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserAdvertisement', function() {
      it('should call deleteUserAdvertisement successfully', function(done) {
        //uncomment below and update the code to test deleteUserAdvertisement
        //instance.deleteUserAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserVehicle', function() {
      it('should call deleteUserVehicle successfully', function(done) {
        //uncomment below and update the code to test deleteUserVehicle
        //instance.deleteUserVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVehiclePhoto', function() {
      it('should call deleteVehiclePhoto successfully', function(done) {
        //uncomment below and update the code to test deleteVehiclePhoto
        //instance.deleteVehiclePhoto(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUserPhotos', function() {
      it('should call getAllUserPhotos successfully', function(done) {
        //uncomment below and update the code to test getAllUserPhotos
        //instance.getAllUserPhotos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavorites1', function() {
      it('should call getFavorites1 successfully', function(done) {
        //uncomment below and update the code to test getFavorites1
        //instance.getFavorites1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdvertisementById', function() {
      it('should call getUserAdvertisementById successfully', function(done) {
        //uncomment below and update the code to test getUserAdvertisementById
        //instance.getUserAdvertisementById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdvertisements', function() {
      it('should call getUserAdvertisements successfully', function(done) {
        //uncomment below and update the code to test getUserAdvertisements
        //instance.getUserAdvertisements(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserDashboard', function() {
      it('should call getUserDashboard successfully', function(done) {
        //uncomment below and update the code to test getUserDashboard
        //instance.getUserDashboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVehicleById', function() {
      it('should call getUserVehicleById successfully', function(done) {
        //uncomment below and update the code to test getUserVehicleById
        //instance.getUserVehicleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVehicles', function() {
      it('should call getUserVehicles successfully', function(done) {
        //uncomment below and update the code to test getUserVehicles
        //instance.getUserVehicles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehiclePhotos', function() {
      it('should call getVehiclePhotos successfully', function(done) {
        //uncomment below and update the code to test getVehiclePhotos
        //instance.getVehiclePhotos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeFromFavorites1', function() {
      it('should call removeFromFavorites1 successfully', function(done) {
        //uncomment below and update the code to test removeFromFavorites1
        //instance.removeFromFavorites1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserAdvertisement', function() {
      it('should call updateUserAdvertisement successfully', function(done) {
        //uncomment below and update the code to test updateUserAdvertisement
        //instance.updateUserAdvertisement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserVehicle', function() {
      it('should call updateUserVehicle successfully', function(done) {
        //uncomment below and update the code to test updateUserVehicle
        //instance.updateUserVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('uploadPhotoToVehicle', function() {
      it('should call uploadPhotoToVehicle successfully', function(done) {
        //uncomment below and update the code to test uploadPhotoToVehicle
        //instance.uploadPhotoToVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
