/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.VehicleControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VehicleControllerApi', function() {
    describe('createVehicle', function() {
      it('should call createVehicle successfully', function(done) {
        //uncomment below and update the code to test createVehicle
        //instance.createVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVehicle', function() {
      it('should call deleteVehicle successfully', function(done) {
        //uncomment below and update the code to test deleteVehicle
        //instance.deleteVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFilteredVehicles', function() {
      it('should call getFilteredVehicles successfully', function(done) {
        //uncomment below and update the code to test getFilteredVehicles
        //instance.getFilteredVehicles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSortedVehicles', function() {
      it('should call getSortedVehicles successfully', function(done) {
        //uncomment below and update the code to test getSortedVehicles
        //instance.getSortedVehicles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehicleById', function() {
      it('should call getVehicleById successfully', function(done) {
        //uncomment below and update the code to test getVehicleById
        //instance.getVehicleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVehicles', function() {
      it('should call getVehicles successfully', function(done) {
        //uncomment below and update the code to test getVehicles
        //instance.getVehicles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVehicle', function() {
      it('should call updateVehicle successfully', function(done) {
        //uncomment below and update the code to test updateVehicle
        //instance.updateVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
