/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddPhotoToVehicleRequest from '../model/AddPhotoToVehicleRequest';
import AdminPageDto from '../model/AdminPageDto';
import AdvertisementDto from '../model/AdvertisementDto';
import PageAdvertisementDto from '../model/PageAdvertisementDto';
import Pageable from '../model/Pageable';
import UserDto from '../model/UserDto';
import VehicleDto from '../model/VehicleDto';
import VehiclePhotoDto from '../model/VehiclePhotoDto';

/**
* AdminPageController service.
* @module api/AdminPageControllerApi
* @version v0
*/
export default class AdminPageControllerApi {

    /**
    * Constructs a new AdminPageControllerApi. 
    * @alias module:api/AdminPageControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addPhotoToVehicle1 operation.
     * @callback module:api/AdminPageControllerApi~addPhotoToVehicle1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/VehiclePhotoDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} vehicleId 
     * @param {Boolean} isMain 
     * @param {Object} opts Optional parameters
     * @param {module:model/AddPhotoToVehicleRequest} [addPhotoToVehicleRequest] 
     * @param {module:api/AdminPageControllerApi~addPhotoToVehicle1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehiclePhotoDto}
     */
    addPhotoToVehicle1(vehicleId, isMain, opts, callback) {
      opts = opts || {};
      let postBody = opts['addPhotoToVehicleRequest'];
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling addPhotoToVehicle1");
      }
      // verify the required parameter 'isMain' is set
      if (isMain === undefined || isMain === null) {
        throw new Error("Missing the required parameter 'isMain' when calling addPhotoToVehicle1");
      }

      let pathParams = {
        'vehicleId': vehicleId
      };
      let queryParams = {
        'isMain': isMain
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehiclePhotoDto;
      return this.apiClient.callApi(
        '/admin-page/vehicle-photos/{vehicleId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the addToFavorites2 operation.
     * @callback module:api/AdminPageControllerApi~addToFavorites2Callback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} userId 
     * @param {Number} advertisementId 
     * @param {module:api/AdminPageControllerApi~addToFavorites2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    addToFavorites2(userId, advertisementId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling addToFavorites2");
      }
      // verify the required parameter 'advertisementId' is set
      if (advertisementId === undefined || advertisementId === null) {
        throw new Error("Missing the required parameter 'advertisementId' when calling addToFavorites2");
      }

      let pathParams = {
        'userId': userId,
        'advertisementId': advertisementId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/admin-page/users/{userId}/favorites/{advertisementId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createAdvertisement1 operation.
     * @callback module:api/AdminPageControllerApi~createAdvertisement1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/AdminPageControllerApi~createAdvertisement1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    createAdvertisement1(advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling createAdvertisement1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/admin-page/advertisements', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createUser1 operation.
     * @callback module:api/AdminPageControllerApi~createUser1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/UserDto} userDto 
     * @param {module:api/AdminPageControllerApi~createUser1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDto}
     */
    createUser1(userDto, callback) {
      let postBody = userDto;
      // verify the required parameter 'userDto' is set
      if (userDto === undefined || userDto === null) {
        throw new Error("Missing the required parameter 'userDto' when calling createUser1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UserDto;
      return this.apiClient.callApi(
        '/admin-page/users/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createVehicle1 operation.
     * @callback module:api/AdminPageControllerApi~createVehicle1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/AdminPageControllerApi~createVehicle1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    createVehicle1(vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling createVehicle1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/admin-page/vehicles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAdvertisement1 operation.
     * @callback module:api/AdminPageControllerApi~deleteAdvertisement1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~deleteAdvertisement1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteAdvertisement1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAdvertisement1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/admin-page/advertisements/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePhoto1 operation.
     * @callback module:api/AdminPageControllerApi~deletePhoto1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~deletePhoto1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePhoto1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deletePhoto1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/admin-page/vehicle-photos/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUser1 operation.
     * @callback module:api/AdminPageControllerApi~deleteUser1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~deleteUser1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUser1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUser1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/admin-page/users/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteVehicle1 operation.
     * @callback module:api/AdminPageControllerApi~deleteVehicle1Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~deleteVehicle1Callback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteVehicle1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteVehicle1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/admin-page/vehicles/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAdvertisementById1 operation.
     * @callback module:api/AdminPageControllerApi~getAdvertisementById1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~getAdvertisementById1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    getAdvertisementById1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAdvertisementById1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/admin-page/advertisements/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAdvertisementsByUser operation.
     * @callback module:api/AdminPageControllerApi~getAdvertisementsByUserCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AdvertisementDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} userId 
     * @param {module:api/AdminPageControllerApi~getAdvertisementsByUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AdvertisementDto>}
     */
    getAdvertisementsByUser(userId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAdvertisementsByUser");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [AdvertisementDto];
      return this.apiClient.callApi(
        '/admin-page/advertisements/user/{userId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllAdvertisements operation.
     * @callback module:api/AdminPageControllerApi~getAllAdvertisementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageAdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Pageable} pageable 
     * @param {module:api/AdminPageControllerApi~getAllAdvertisementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageAdvertisementDto}
     */
    getAllAdvertisements(pageable, callback) {
      let postBody = null;
      // verify the required parameter 'pageable' is set
      if (pageable === undefined || pageable === null) {
        throw new Error("Missing the required parameter 'pageable' when calling getAllAdvertisements");
      }

      let pathParams = {
      };
      let queryParams = {
        'pageable': pageable
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageAdvertisementDto;
      return this.apiClient.callApi(
        '/admin-page/advertisements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllPhotos1 operation.
     * @callback module:api/AdminPageControllerApi~getAllPhotos1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehiclePhotoDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/AdminPageControllerApi~getAllPhotos1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehiclePhotoDto>}
     */
    getAllPhotos1(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehiclePhotoDto];
      return this.apiClient.callApi(
        '/admin-page/vehicle-photos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllUsers1 operation.
     * @callback module:api/AdminPageControllerApi~getAllUsers1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/UserDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/AdminPageControllerApi~getAllUsers1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/UserDto>}
     */
    getAllUsers1(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UserDto];
      return this.apiClient.callApi(
        '/admin-page/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllVehicles operation.
     * @callback module:api/AdminPageControllerApi~getAllVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/AdminPageControllerApi~getAllVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getAllVehicles(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/admin-page/vehicles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDashboard operation.
     * @callback module:api/AdminPageControllerApi~getDashboardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AdminPageDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} [start] 
     * @param {String} [end] 
     * @param {module:api/AdminPageControllerApi~getDashboardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdminPageDto}
     */
    getDashboard(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'start': opts['start'],
        'end': opts['end']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AdminPageDto;
      return this.apiClient.callApi(
        '/admin-page/dashboard', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavorites2 operation.
     * @callback module:api/AdminPageControllerApi~getFavorites2Callback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} userId 
     * @param {module:api/AdminPageControllerApi~getFavorites2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFavorites2(userId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavorites2");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/admin-page/users/{userId}/favorites', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFilteredVehicles1 operation.
     * @callback module:api/AdminPageControllerApi~getFilteredVehicles1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} [brand] 
     * @param {String} [model] 
     * @param {Number} [year] 
     * @param {Number} [minPrice] 
     * @param {Number} [maxPrice] 
     * @param {Number} [minMileage] 
     * @param {Number} [maxMileage] 
     * @param {String} [fuelType] 
     * @param {String} [transmission] 
     * @param {module:api/AdminPageControllerApi~getFilteredVehicles1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getFilteredVehicles1(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'brand': opts['brand'],
        'model': opts['model'],
        'year': opts['year'],
        'minPrice': opts['minPrice'],
        'maxPrice': opts['maxPrice'],
        'minMileage': opts['minMileage'],
        'maxMileage': opts['maxMileage'],
        'fuelType': opts['fuelType'],
        'transmission': opts['transmission']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/admin-page/vehicles/filter', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPhotoById1 operation.
     * @callback module:api/AdminPageControllerApi~getPhotoById1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/VehiclePhotoDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~getPhotoById1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehiclePhotoDto}
     */
    getPhotoById1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPhotoById1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = VehiclePhotoDto;
      return this.apiClient.callApi(
        '/admin-page/vehicle-photos/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSortedVehicles1 operation.
     * @callback module:api/AdminPageControllerApi~getSortedVehicles1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sortBy 
     * @param {String} order 
     * @param {module:api/AdminPageControllerApi~getSortedVehicles1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getSortedVehicles1(sortBy, order, callback) {
      let postBody = null;
      // verify the required parameter 'sortBy' is set
      if (sortBy === undefined || sortBy === null) {
        throw new Error("Missing the required parameter 'sortBy' when calling getSortedVehicles1");
      }
      // verify the required parameter 'order' is set
      if (order === undefined || order === null) {
        throw new Error("Missing the required parameter 'order' when calling getSortedVehicles1");
      }

      let pathParams = {
      };
      let queryParams = {
        'sortBy': sortBy,
        'order': order
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/admin-page/vehicles/sorted', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserById1 operation.
     * @callback module:api/AdminPageControllerApi~getUserById1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~getUserById1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDto}
     */
    getUserById1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getUserById1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UserDto;
      return this.apiClient.callApi(
        '/admin-page/users/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehicleById1 operation.
     * @callback module:api/AdminPageControllerApi~getVehicleById1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdminPageControllerApi~getVehicleById1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    getVehicleById1(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getVehicleById1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/admin-page/vehicles/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehiclesByUser operation.
     * @callback module:api/AdminPageControllerApi~getVehiclesByUserCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} userId 
     * @param {module:api/AdminPageControllerApi~getVehiclesByUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getVehiclesByUser(userId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getVehiclesByUser");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/admin-page/vehicles/user/{userId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the removeFromFavorites2 operation.
     * @callback module:api/AdminPageControllerApi~removeFromFavorites2Callback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} userId 
     * @param {Number} advertisementId 
     * @param {module:api/AdminPageControllerApi~removeFromFavorites2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    removeFromFavorites2(userId, advertisementId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling removeFromFavorites2");
      }
      // verify the required parameter 'advertisementId' is set
      if (advertisementId === undefined || advertisementId === null) {
        throw new Error("Missing the required parameter 'advertisementId' when calling removeFromFavorites2");
      }

      let pathParams = {
        'userId': userId,
        'advertisementId': advertisementId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/admin-page/users/{userId}/favorites/{advertisementId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAdvertisement1 operation.
     * @callback module:api/AdminPageControllerApi~updateAdvertisement1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/AdminPageControllerApi~updateAdvertisement1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    updateAdvertisement1(id, advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAdvertisement1");
      }
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling updateAdvertisement1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/admin-page/advertisements/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUser1 operation.
     * @callback module:api/AdminPageControllerApi~updateUser1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/UserDto} userDto 
     * @param {module:api/AdminPageControllerApi~updateUser1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDto}
     */
    updateUser1(id, userDto, callback) {
      let postBody = userDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUser1");
      }
      // verify the required parameter 'userDto' is set
      if (userDto === undefined || userDto === null) {
        throw new Error("Missing the required parameter 'userDto' when calling updateUser1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UserDto;
      return this.apiClient.callApi(
        '/admin-page/users/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateVehicle1 operation.
     * @callback module:api/AdminPageControllerApi~updateVehicle1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/AdminPageControllerApi~updateVehicle1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    updateVehicle1(id, vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateVehicle1");
      }
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling updateVehicle1");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/admin-page/vehicles/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
