/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Advertisement from '../model/Advertisement';
import AdvertisementDto from '../model/AdvertisementDto';
import PageAdvertisementDto from '../model/PageAdvertisementDto';

/**
* AdvertisementController service.
* @module api/AdvertisementControllerApi
* @version v0
*/
export default class AdvertisementControllerApi {

    /**
    * Constructs a new AdvertisementControllerApi. 
    * @alias module:api/AdvertisementControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createAdvertisement operation.
     * @callback module:api/AdvertisementControllerApi~createAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Advertisement} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/AdvertisementControllerApi~createAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Advertisement}
     */
    createAdvertisement(advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling createAdvertisement");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Advertisement;
      return this.apiClient.callApi(
        '/advertisements', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAdvertisement operation.
     * @callback module:api/AdvertisementControllerApi~deleteAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdvertisementControllerApi~deleteAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteAdvertisement(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAdvertisement");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/advertisements/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAdvertisementById operation.
     * @callback module:api/AdvertisementControllerApi~getAdvertisementByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Advertisement} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/AdvertisementControllerApi~getAdvertisementByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Advertisement}
     */
    getAdvertisementById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAdvertisementById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Advertisement;
      return this.apiClient.callApi(
        '/advertisements/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAdvertisements operation.
     * @callback module:api/AdvertisementControllerApi~getAdvertisementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageAdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} page 
     * @param {Object} opts Optional parameters
     * @param {Number} [size = 50)] 
     * @param {module:api/AdvertisementControllerApi~getAdvertisementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageAdvertisementDto}
     */
    getAdvertisements(page, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'page' is set
      if (page === undefined || page === null) {
        throw new Error("Missing the required parameter 'page' when calling getAdvertisements");
      }

      let pathParams = {
      };
      let queryParams = {
        'page': page,
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageAdvertisementDto;
      return this.apiClient.callApi(
        '/advertisements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAdvertisement operation.
     * @callback module:api/AdvertisementControllerApi~updateAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Advertisement} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/AdvertisementControllerApi~updateAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Advertisement}
     */
    updateAdvertisement(id, advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateAdvertisement");
      }
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling updateAdvertisement");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Advertisement;
      return this.apiClient.callApi(
        '/advertisements/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
