/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EmailDto from '../model/EmailDto';

/**
* EmailController service.
* @module api/EmailControllerApi
* @version v0
*/
export default class EmailControllerApi {

    /**
    * Constructs a new EmailControllerApi. 
    * @alias module:api/EmailControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the resetPassword operation.
     * @callback module:api/EmailControllerApi~resetPasswordCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/EmailDto} emailDto 
     * @param {module:api/EmailControllerApi~resetPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    resetPassword(emailDto, callback) {
      let postBody = emailDto;
      // verify the required parameter 'emailDto' is set
      if (emailDto === undefined || emailDto === null) {
        throw new Error("Missing the required parameter 'emailDto' when calling resetPassword");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/email/reset-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the resetPasswordRequest operation.
     * @callback module:api/EmailControllerApi~resetPasswordRequestCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/EmailDto} emailDto 
     * @param {module:api/EmailControllerApi~resetPasswordRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    resetPasswordRequest(emailDto, callback) {
      let postBody = emailDto;
      // verify the required parameter 'emailDto' is set
      if (emailDto === undefined || emailDto === null) {
        throw new Error("Missing the required parameter 'emailDto' when calling resetPasswordRequest");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/email/reset-password-request', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the verifyEmail operation.
     * @callback module:api/EmailControllerApi~verifyEmailCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} token 
     * @param {module:api/EmailControllerApi~verifyEmailCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    verifyEmail(token, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling verifyEmail");
      }

      let pathParams = {
      };
      let queryParams = {
        'token': token
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/email/verify', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
