/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddPhotoToVehicleRequest from '../model/AddPhotoToVehicleRequest';
import AdvertisementDto from '../model/AdvertisementDto';
import PageAdvertisementDto from '../model/PageAdvertisementDto';
import UserPageDto from '../model/UserPageDto';
import VehicleDto from '../model/VehicleDto';
import VehiclePhotoDto from '../model/VehiclePhotoDto';

/**
* UserPageController service.
* @module api/UserPageControllerApi
* @version v0
*/
export default class UserPageControllerApi {

    /**
    * Constructs a new UserPageControllerApi. 
    * @alias module:api/UserPageControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addToFavorites1 operation.
     * @callback module:api/UserPageControllerApi~addToFavorites1Callback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} advertisementId 
     * @param {module:api/UserPageControllerApi~addToFavorites1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    addToFavorites1(advertisementId, callback) {
      let postBody = null;
      // verify the required parameter 'advertisementId' is set
      if (advertisementId === undefined || advertisementId === null) {
        throw new Error("Missing the required parameter 'advertisementId' when calling addToFavorites1");
      }

      let pathParams = {
        'advertisementId': advertisementId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user-page/favorites/{advertisementId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createUserAdvertisement operation.
     * @callback module:api/UserPageControllerApi~createUserAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/UserPageControllerApi~createUserAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    createUserAdvertisement(advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling createUserAdvertisement");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/user-page/advertisements', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createUserVehicle operation.
     * @callback module:api/UserPageControllerApi~createUserVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/UserPageControllerApi~createUserVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    createUserVehicle(vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling createUserVehicle");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/user-page/vehicles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUserAdvertisement operation.
     * @callback module:api/UserPageControllerApi~deleteUserAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/UserPageControllerApi~deleteUserAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUserAdvertisement(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUserAdvertisement");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/user-page/advertisements/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUserVehicle operation.
     * @callback module:api/UserPageControllerApi~deleteUserVehicleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/UserPageControllerApi~deleteUserVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteUserVehicle(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUserVehicle");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/user-page/vehicles/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteVehiclePhoto operation.
     * @callback module:api/UserPageControllerApi~deleteVehiclePhotoCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} photoId 
     * @param {module:api/UserPageControllerApi~deleteVehiclePhotoCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteVehiclePhoto(photoId, callback) {
      let postBody = null;
      // verify the required parameter 'photoId' is set
      if (photoId === undefined || photoId === null) {
        throw new Error("Missing the required parameter 'photoId' when calling deleteVehiclePhoto");
      }

      let pathParams = {
        'photoId': photoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/user-page/photos/{photoId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllUserPhotos operation.
     * @callback module:api/UserPageControllerApi~getAllUserPhotosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehiclePhotoDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserPageControllerApi~getAllUserPhotosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehiclePhotoDto>}
     */
    getAllUserPhotos(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehiclePhotoDto];
      return this.apiClient.callApi(
        '/user-page/photos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavorites1 operation.
     * @callback module:api/UserPageControllerApi~getFavorites1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserPageControllerApi~getFavorites1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getFavorites1(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/user-page/favorites', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserAdvertisementById operation.
     * @callback module:api/UserPageControllerApi~getUserAdvertisementByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/UserPageControllerApi~getUserAdvertisementByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    getUserAdvertisementById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getUserAdvertisementById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/user-page/advertisements/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserAdvertisements operation.
     * @callback module:api/UserPageControllerApi~getUserAdvertisementsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageAdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 50)] 
     * @param {module:api/UserPageControllerApi~getUserAdvertisementsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageAdvertisementDto}
     */
    getUserAdvertisements(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageAdvertisementDto;
      return this.apiClient.callApi(
        '/user-page/advertisements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserDashboard operation.
     * @callback module:api/UserPageControllerApi~getUserDashboardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserPageDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserPageControllerApi~getUserDashboardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserPageDto}
     */
    getUserDashboard(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UserPageDto;
      return this.apiClient.callApi(
        '/user-page/dashboard', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserVehicleById operation.
     * @callback module:api/UserPageControllerApi~getUserVehicleByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/UserPageControllerApi~getUserVehicleByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    getUserVehicleById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getUserVehicleById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/user-page/vehicles/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getUserVehicles operation.
     * @callback module:api/UserPageControllerApi~getUserVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserPageControllerApi~getUserVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getUserVehicles(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/user-page/vehicles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehiclePhotos operation.
     * @callback module:api/UserPageControllerApi~getVehiclePhotosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehiclePhotoDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} vehicleId 
     * @param {module:api/UserPageControllerApi~getVehiclePhotosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehiclePhotoDto>}
     */
    getVehiclePhotos(vehicleId, callback) {
      let postBody = null;
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling getVehiclePhotos");
      }

      let pathParams = {
        'vehicleId': vehicleId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehiclePhotoDto];
      return this.apiClient.callApi(
        '/user-page/vehicles/{vehicleId}/photos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the removeFromFavorites1 operation.
     * @callback module:api/UserPageControllerApi~removeFromFavorites1Callback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} advertisementId 
     * @param {module:api/UserPageControllerApi~removeFromFavorites1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    removeFromFavorites1(advertisementId, callback) {
      let postBody = null;
      // verify the required parameter 'advertisementId' is set
      if (advertisementId === undefined || advertisementId === null) {
        throw new Error("Missing the required parameter 'advertisementId' when calling removeFromFavorites1");
      }

      let pathParams = {
        'advertisementId': advertisementId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user-page/favorites/{advertisementId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUserAdvertisement operation.
     * @callback module:api/UserPageControllerApi~updateUserAdvertisementCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AdvertisementDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/AdvertisementDto} advertisementDto 
     * @param {module:api/UserPageControllerApi~updateUserAdvertisementCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AdvertisementDto}
     */
    updateUserAdvertisement(id, advertisementDto, callback) {
      let postBody = advertisementDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUserAdvertisement");
      }
      // verify the required parameter 'advertisementDto' is set
      if (advertisementDto === undefined || advertisementDto === null) {
        throw new Error("Missing the required parameter 'advertisementDto' when calling updateUserAdvertisement");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AdvertisementDto;
      return this.apiClient.callApi(
        '/user-page/advertisements/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUserVehicle operation.
     * @callback module:api/UserPageControllerApi~updateUserVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/UserPageControllerApi~updateUserVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    updateUserVehicle(id, vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUserVehicle");
      }
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling updateUserVehicle");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/user-page/vehicles/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the uploadPhotoToVehicle operation.
     * @callback module:api/UserPageControllerApi~uploadPhotoToVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehiclePhotoDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} vehicleId 
     * @param {Object} opts Optional parameters
     * @param {Boolean} [isMain = false)] 
     * @param {module:model/AddPhotoToVehicleRequest} [addPhotoToVehicleRequest] 
     * @param {module:api/UserPageControllerApi~uploadPhotoToVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehiclePhotoDto}
     */
    uploadPhotoToVehicle(vehicleId, opts, callback) {
      opts = opts || {};
      let postBody = opts['addPhotoToVehicleRequest'];
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling uploadPhotoToVehicle");
      }

      let pathParams = {
        'vehicleId': vehicleId
      };
      let queryParams = {
        'isMain': opts['isMain']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehiclePhotoDto;
      return this.apiClient.callApi(
        '/user-page/vehicles/{vehicleId}/photos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
