/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddPhotoToVehicleRequest from '../model/AddPhotoToVehicleRequest';
import VehiclePhoto from '../model/VehiclePhoto';
import VehiclePhotoDto from '../model/VehiclePhotoDto';

/**
* VehiclePhotoController service.
* @module api/VehiclePhotoControllerApi
* @version v0
*/
export default class VehiclePhotoControllerApi {

    /**
    * Constructs a new VehiclePhotoControllerApi. 
    * @alias module:api/VehiclePhotoControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addPhotoToVehicle operation.
     * @callback module:api/VehiclePhotoControllerApi~addPhotoToVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehiclePhoto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} vehicleId 
     * @param {Boolean} isMain 
     * @param {String} username 
     * @param {Object} opts Optional parameters
     * @param {module:model/AddPhotoToVehicleRequest} [addPhotoToVehicleRequest] 
     * @param {module:api/VehiclePhotoControllerApi~addPhotoToVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehiclePhoto}
     */
    addPhotoToVehicle(vehicleId, isMain, username, opts, callback) {
      opts = opts || {};
      let postBody = opts['addPhotoToVehicleRequest'];
      // verify the required parameter 'vehicleId' is set
      if (vehicleId === undefined || vehicleId === null) {
        throw new Error("Missing the required parameter 'vehicleId' when calling addPhotoToVehicle");
      }
      // verify the required parameter 'isMain' is set
      if (isMain === undefined || isMain === null) {
        throw new Error("Missing the required parameter 'isMain' when calling addPhotoToVehicle");
      }
      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling addPhotoToVehicle");
      }

      let pathParams = {
      };
      let queryParams = {
        'vehicleId': vehicleId,
        'isMain': isMain,
        'username': username
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehiclePhoto;
      return this.apiClient.callApi(
        '/vehicle-photos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePhoto operation.
     * @callback module:api/VehiclePhotoControllerApi~deletePhotoCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/VehiclePhotoControllerApi~deletePhotoCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePhoto(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deletePhoto");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/vehicle-photos/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllPhotos operation.
     * @callback module:api/VehiclePhotoControllerApi~getAllPhotosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehiclePhotoDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/VehiclePhotoControllerApi~getAllPhotosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehiclePhotoDto>}
     */
    getAllPhotos(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehiclePhotoDto];
      return this.apiClient.callApi(
        '/vehicle-photos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPhotoById operation.
     * @callback module:api/VehiclePhotoControllerApi~getPhotoByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehiclePhotoDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/VehiclePhotoControllerApi~getPhotoByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehiclePhotoDto}
     */
    getPhotoById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPhotoById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = VehiclePhotoDto;
      return this.apiClient.callApi(
        '/vehicle-photos/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
