/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import VehicleDto from '../model/VehicleDto';

/**
* VehicleController service.
* @module api/VehicleControllerApi
* @version v0
*/
export default class VehicleControllerApi {

    /**
    * Constructs a new VehicleControllerApi. 
    * @alias module:api/VehicleControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createVehicle operation.
     * @callback module:api/VehicleControllerApi~createVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/VehicleControllerApi~createVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    createVehicle(vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling createVehicle");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/vehicles', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteVehicle operation.
     * @callback module:api/VehicleControllerApi~deleteVehicleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/VehicleControllerApi~deleteVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteVehicle(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteVehicle");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/vehicles/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFilteredVehicles operation.
     * @callback module:api/VehicleControllerApi~getFilteredVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} [brand] 
     * @param {String} [model] 
     * @param {Number} [year] 
     * @param {Number} [minPrice] 
     * @param {Number} [maxPrice] 
     * @param {Number} [minMileage] 
     * @param {Number} [maxMileage] 
     * @param {String} [fuelType] 
     * @param {String} [transmission] 
     * @param {module:api/VehicleControllerApi~getFilteredVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getFilteredVehicles(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'brand': opts['brand'],
        'model': opts['model'],
        'year': opts['year'],
        'minPrice': opts['minPrice'],
        'maxPrice': opts['maxPrice'],
        'minMileage': opts['minMileage'],
        'maxMileage': opts['maxMileage'],
        'fuelType': opts['fuelType'],
        'transmission': opts['transmission']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/vehicles/filter', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSortedVehicles operation.
     * @callback module:api/VehicleControllerApi~getSortedVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} sortBy 
     * @param {String} order 
     * @param {module:api/VehicleControllerApi~getSortedVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getSortedVehicles(sortBy, order, callback) {
      let postBody = null;
      // verify the required parameter 'sortBy' is set
      if (sortBy === undefined || sortBy === null) {
        throw new Error("Missing the required parameter 'sortBy' when calling getSortedVehicles");
      }
      // verify the required parameter 'order' is set
      if (order === undefined || order === null) {
        throw new Error("Missing the required parameter 'order' when calling getSortedVehicles");
      }

      let pathParams = {
      };
      let queryParams = {
        'sortBy': sortBy,
        'order': order
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/vehicles/sorted', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehicleById operation.
     * @callback module:api/VehicleControllerApi~getVehicleByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/VehicleControllerApi~getVehicleByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    getVehicleById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getVehicleById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/vehicles/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVehicles operation.
     * @callback module:api/VehicleControllerApi~getVehiclesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/VehicleControllerApi~getVehiclesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VehicleDto>}
     */
    getVehicles(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VehicleDto];
      return this.apiClient.callApi(
        '/vehicles', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateVehicle operation.
     * @callback module:api/VehicleControllerApi~updateVehicleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VehicleDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/VehicleDto} vehicleDto 
     * @param {module:api/VehicleControllerApi~updateVehicleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VehicleDto}
     */
    updateVehicle(id, vehicleDto, callback) {
      let postBody = vehicleDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateVehicle");
      }
      // verify the required parameter 'vehicleDto' is set
      if (vehicleDto === undefined || vehicleDto === null) {
        throw new Error("Missing the required parameter 'vehicleDto' when calling updateVehicle");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = VehicleDto;
      return this.apiClient.callApi(
        '/vehicles/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
